"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from glob import glob
from setuptools import setup

APP = ['InfoWin.py']
DATA_FILES = [
    ('', glob('*.png')),
    ('', ['about.txt'])
]
OPTIONS = {
    "iconfile": "lpico.png",
    "plist": {"CFBundleShortVersionString": "1.0"}
}

setup(
    app=APP,
    name="Lektionsplaneraren",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
